[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18"]

[phases.install]
cmds = [
  "echo 'Instalando dependências do Node...'",
  "cd api/node && npm install",
  "cd ../.."
]

[start]
cmd = "sh start_railway.sh"
